import "./globals.css";
import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const dM_Sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abdurahman Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dM_Sans.className}>{children}</body>
    </html>
  );
}
